# General
site_name: Shippable Docs
repo_url: https://github.com/Shippable/docsv2

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Overview:
  - What is Shippable?: index.md
  - FAQ: faq.md
- Continuous Integration (CI):
  - Overview: ci/overview.md
  - What is supported?: ci/supported.md
  - Running a build: ci/runFirstBuild.md
  - Build config: ci/shippableyml.md
  - Languages:
    - Node.js: ci/languages/node.md
    - Python: ci/languages/python.md
    - Java: ci/languages/java.md
    - Clojure: ci/languages/clojure.md
    - Ruby: ci/languages/ruby.md
    - Go: ci/languages/go.md
    - PHP: ci/languages/php.md
    - Scala: ci/languages/scala.md
    - C: ci/languages/objc.md
    - Custom Images: ci/languages/customImages.md
  - Advanced Options:
    - Environment Variables: ci/advancedOptions/envVar.md
    - Including/Excluding branches: ci/advancedOptions/branches.md
    - Matrix builds: ci/advancedOptions/matrixBuilds.md
    - Caching: ci/advancedOptions/caching.md
    - Using git submodules: ci/advancedOptions/gitSubmodules.md
    - Shippable_retry: ci/advancedOptions/retry.md
    - Running builds on your own machines (BYON): ci/advancedOptions/byonOverview.md
    - Images: ci/advancedOptions/images.md
    - Timeouts: ci/advancedOptions/timeouts.md
    - Node Machine Images: ci/advancedOptions/machineImages.md
  - Integrations:
    - Source Control Systems:
      - Overview: ci/integrations/scm/scmOverview.md
      - GitHub: ci/integrations/scm/github.md
      - GitHub Enterprise: ci/integrations/scm/githubEnterprise.md
      - Bitbucket: ci/integrations/scm/bitbucket.md
      - Bitbucket Server: ci/integrations/scm/bitbucketServer.md
      - GitLab: ci/integrations/scm/gitlab.md
    - Notifications:
      - Slack: ci/integrations/notifications/slack.md
      - Email: ci/integrations/notifications/email.md
      - HipChat: ci/integrations/notifications/hipchat.md
      - IRC: ci/integrations/notifications/irc.md
    - Image Registries:
      - Docker Hub: ci/integrations/imageRegistries/dockerHub.md
      - Docker Trusted Registry: ci/integrations/imageRegistries/dockerTrustedRegistry.md
      - Amazon EC2 Container Registry (ECR): ci/integrations/imageRegistries/ecr.md
      - Google Container Registry (GCR): ci/integrations/imageRegistries/gcr.md
      - Quay.io: ci/integrations/imageRegistries/quay.md
      - Any Private Registry: ci/integrations/imageRegistries/privateRegistry.md
    - Container Services:
      - Amazon EC2 Container Service (ECS): ci/integrations/containerServices/ecs.md
      - Google Container Engine (GKE): ci/integrations/containerServices/gke.md
      - Docker Cloud: ci/integrations/containerServices/dockerCloud.md
      - Docker Datacenter: ci/integrations/containerServices/dockerDatacenter.md
    - Deploy:
      - AWS Elastic Beanstalk: ci/integrations/deploy/eb.md
      - Webhooks: ci/integrations/deploy/webhooks.md
    - Keys:
      - SSH: ci/integrations/keys/ssh.md
      - PEM:  ci/integrations/keys/pem.md
  - Permissions: ci/permissions.md
  - Troubleshooting CI: ci/troubleshoot.md
- Pipelines:
  - Overview: pipelines/overview.md
  - Resources: pipelines/resources.md
  - Jobs: pipelines/jobs.md
  - Triggers: pipelines/triggers.md
  - Sample: tutorials/samplePipeline.md
  - FAQ: pipelines/faq.md
  - Troubleshooting: pipelines/troubleshoot.md
- Navigating the UI:
  - Home: navigatingUI/home.md
  - Account:
    - Account: navigatingUI/accountSettings/accounts.md
    - Integrations: navigatingUI/accountSettings/integrations.md
    - Cards: navigatingUI/accountSettings/cards.md
    - Images: navigatingUI/accountSettings/images.md
    - API: navigatingUI/accountSettings/api.md
  - Subscription:
    - CI: navigatingUI/subscriptions/ci.md
    - Pipelines: navigatingUI/subscriptions/pipelines.md
    - Settings: navigatingUI/subscriptions/settings.md
  - Project:
    - Status: navigatingUI/projects/status.md
    - Settings: navigatingUI/projects/settings.md
  - Build:
    - Overview: navigatingUI/builds/overview.md
    - Detail: navigatingUI/builds/detail.md
- API:
  - Overview: api/api.md
  - Account routes: api/apiAccount.md
  - Subscription routes: api/apiSubscription.md
  - Project routes: api/apiProject.md
  - Job routes: api/apiJob.md
  - Run routes: api/apiRuns.md
  - Status Code Mapping: api/apiStatusMapping.md
- Tutorials:
  - Pipelines:
    - How to add resources: tutorials/howToAddSyncRepos.md
  - How to add integrations: tutorials/addAccountIntegrations.md
  - Running a sample CI build: tutorials/runSampleCIBuild.md
  - Deploying a sample appliation: tutorials/samplePipeline.md
  - Source Control System:
    - Using GitHub: tutorials/usingGitHub.md
    - Using GitHub Enterprise: tutorials/usingGitHubEnterprise.md
    - Using Bitbucket: tutorials/usingBitbucket.md
    - Using Bitbucket Server: tutorials/usingBitbucketServer.md
    - Using GitLab: tutorials/usingGitLab.md
    - Linking GitHub and Bitbucket accounts: tutorials/linkGitHubAndBitbucket.md
  - Amazon:
    - Deploy to AWS CodeDeploy: tutorials/usingCodeDeploy.md
    - Deploy to Amazon Opsworks: tutorials/usingOpsWorks.md
    - Deploy to Amazon EC2 Container Registry (ECR): test.md
    - Deploy to AWS Elastic Beanstalk: test.md
    - Deploy to Amazon EC2 Container Service (ECS): test.md
  - Google:
    - Deploy to Google Container Registry (GCR): test.md
    - Deploy to Google Container Engine (GKE): test.md
  - Docker:
    - Deploy to Docker Hub: test.md
    - Deploy to Docker Trusted Registry: test.md
    - Deploy to Docker Datacenter: tutorials/usingDockerDatacenter.md
    - Deploy to Docker Cloud: test.md
  - Microsoft:
    - Deploy to DC/OS on Azure: test.md
    - Deploy to Docker Swarm on Azure: test.md
    - Deploy to Azure Container Service (ACS): test.md
  - Deploy to Quay.io: test.md
  - Deploy to any private registry: test.md
  - Languages Based:
    - test: test.md
  - Pushing to multiple registries: test.md
  - Pushing multiple tags: test.md
  - Overriding the default build image: test.md
  - Building your CI image: test.md
  - Pulling your CI image from a Docker registry: test.md
  - Setting up matrix builds: test.md
  - Setting up git submodules: test.md
  - Using Shippable_retry: test.md
  - Using Caching: test.md
  - Using matrix to parallelize builds: test.md
  - Running multiple docker push: test.md
  - Deploy to Heroku: tutorials/usingHeroku.md
  - Deploy to Digital Ocean: tutorials/usingDigitalOcean.md
  - Monitor your Docker images for updates: tutorials/howToMonitorDockerImages.md
