# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Getting Started: index.md
- CI/CD:
  - Overview: ci_overview.md
  - CI Subscription Dashboard: ci_dashboard.md
  - CI Subscription Billing: ci_billing.md
  - CI Subscription Settings: ci_settings.md
  - Project Dashboard: project_dashboard.md
  - PR Builds: pr_builds.md
  - Queued Builds: queued_builds.md
  - Project Settings: project_settings.md
  - Build Dashboard: build_dashboard.md
- Formations:
  - Overview: formations_overview.md
  - Formations Dashboard: formations_status.md
  - Formation Settings: formation_settings.md
  - Formations Billing: formations_billing.md
- Lighthouse: lighthouse.md
- Account:
  - Account Settings: account_settings.md
  - Integrations: integrations.md
  - Payment Methods: payment_methods.md
- How To:
  - Link GitHub and Bitbucket Accounts: link_gh_and_bb.md
  - Use CI with Test and Coverage: build_case2.md
  - Use a Docker Registry: docker_registries.md
  - Do a Docker Build: docker_build.md
  - Use Specific Languages for CI: languages.md
  - Use Shippable CI with Gitlab: using_gitlab.md
  - Deploy to Heroku: heroku.md
  - Deploy to Amazon Elastic Beanstalk: beanstalk.md
  - Deploy to AWS OpsWorks: opswork.md
  - Deploy to Google App Engine: appengine.md
  - Deploy to Red Hat OpenShift: openshift.md
  - Deploy to DigitalOcean: digitalocean.md
  - Deploy to AWS CodeDeploy: codedeploy.md
- API: api.md
- Reference:
  - FAQ: faq.md
  - How the Build works: basic_flow.md
  - YML Reference: yml_reference.md
  - Supported Languages: supported_services.md
  - Access and Permissions: permissions.md
  - Glossary: glossary.md
