# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Getting Started:
  - Overview: index.md
  - Concepts: gs_concepts.md
  - What is supported?: gs_supported.md
  - Plans & Pricing: gs_plans.md
  - Your Shippable Account: acc_overview.md 
  - Running a sample build: gs_ci_sample.md
  - Deploying sample application: gs_deploy_sample.md  
- Shippable CI:
  - Overview: ci_overview.md
  - Subscriptions: ci_subscriptions.md
  - Projects: ci_projects.md
  - Builds: ci_builds.md
  - Configuring your build: ci_configure.md
  - Language help: ci_languages.md
  - Docker support: ci_docker.md
  - Running a sample build: gs_ci_sample.md
  - FAQ: ci_faq.md
- Shippable Flow:
  - Overview: flow_overview.md
  - Subscriptions: flow_subscriptions.md
  - Application infrastructure: flow_infrastructure.md  
  - Configuring your services: flow_configure.md
  - Deploying and managing applications: flow_manage.md
  - Moving across clouds: flow_clouds.md
  - Deploy a sample app: gs_deploy_sample.md
  - FAQ: flow_faq.md
  - Troubleshooting: flow_troubleshoot.md
- Integrations: 
  - Overview: int_overview.md
  - Source control providers: int_scm.md
  - Docker registries: int_docker_registries.md
  - Container services: int_container_services.md
  - Notification providers: int_notifications.md
- Tutorials: ht_overview.md
- API: api.md
- Lighthouse: lighthouse.md
- YML Reference: yml_reference.md

