# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
  - [index.md, Getting Started]

  - [ci_overview.md, CI/CD, Overview]
  - [ci_dashboard.md, CI/CD, CI Subscription Dashboard]
  - [ci_billing.md, CI/CD, CI Subscription Billing]
  - [ci_settings.md, CI/CD, CI Subscription Settings]
  - [project_dashboard.md, CI/CD, Project Dashboard]
  - [pr_builds.md, CI/CD, PR Builds]
  - [queued_builds.md, CI/CD, Queued Builds]
  - [project_settings.md, CI/CD, Project Settings]
  - [build_dashboard.md, CI/CD, Build Dashboard]

  - [formations_overview.md, Formations, Overview]
  - [formations_status.md, Formations, Formations Dashboard]
 # - [formation_services.md, Shippable Formations, Formation Services]
  - [formation_settings.md, Formations, Formation Settings]
  - [formations_billing.md, Formations, Formations Billing]

  - [lighthouse.md, Lighthouse]

  - [account_settings.md, Account, Account Settings]
  - [integrations.md, Account, Integrations]
  - [payment_methods.md, Account, Payment Methods]

  - [link_gh_and_bb.md, How To, Link GitHub and Bitbucket Accounts]
  - [build_case2.md, How To, Use CI with Test and Coverage]
  - [docker_registries.md, How To, Use a Docker Registry]
  - [docker_build.md, How To, Do a Docker Build]
  - [languages.md, How To, Use Specific Languages for CI]
  #- [sample_formation.md, How To, Create a Sample Formation]
  - [using_gitlab.md, How To, Use Shippable CI with Gitlab]
  - [heroku.md, How To, Deploy to Heroku]
  - [beanstalk.md, How To, Deploy to Amazon Elastic Beanstalk]
  - [opswork.md, How To, Deploy to AWS OpsWorks]
  - [appengine.md, How To, Deploy to Google App Engine]
  - [openshift.md, How To, Deploy to Red Hat OpenShift]
  - [digitalocean.md, How To, Deploy to DigitalOcean]
  - [codedeploy.md, How To, Deploy to AWS CodeDeploy]

  - [api.md, API]

  - [faq.md, Reference, FAQ]
  - [basic_flow.md, Reference, How the Build works]
  - [yml_reference.md, Reference, YML Reference]
  - [supported_services.md, Reference, Supported Languages]
  - [permissions.md, Reference, Access and Permissions]
  - [glossary.md, Reference, Glossary]
