# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Overview:
  - What is Shippable?: index.md
  - FAQ: faq.md
- Continuous Integration (CI):
  - Overview: continuous_integration/ci_overview.md
  - What is supported?: continuous_integration/supported.md
  - Running your first build: continuous_integration/run_first_build.md
  - Defaults:
    - Environment Variables: continuous_integration/defaults/env_var.md
    - Images: continuous_integration/defaults/images.md
    - Timeouts: continuous_integration/defaults/timeouts.md
    - Node Machine Images: continuous_integration/defaults/machine_images.md
  - Configuring your environment:
    - Languages:
      - Node.js: continuous_integration/languages/node.md
      - Python: continuous_integration/languages/python.md
      - Ruby:
        - GEMFILEs behaviour: continuous_integration/languages/ruby.md
      - Java:
        - JDK behaviour: continuous_integration/languages/java.md
      - Clojure: continuous_integration/languages/clojure.md
      - Go: continuous_integration/languages/go.md
      - PHP: continuous_integration/languages/php.md
      - Scala: continuous_integration/languages/scala.md
      - C: continuous_integration/languages/objc.md
      - Custom Images: continuous_integration/languages/custom_images.md
    - Advanced Options:
      - Custom Environment Variables: continuous_integration/advanced_options/custom_env_var.md
      - Including/Excluding branches: continuous_integration/advanced_options/include_exclude_branches.md
      - Matrix builds: continuous_integration/advanced_options/matrix_builds.md
      - Caching: continuous_integration/advanced_options/caching.md
      - Using git submodules: continuous_integration/advanced_options/git_submodules.md
      - Shippable_retry: continuous_integration/advanced_options/shippable_retry.md
  - Configuring your CI:
    - The ci section: continuous_integration/build_ci.md
  - Configuring Post CI: continuous_integration/post_ci.md
  - Integrations:
    - Source Control Systems:
      - GitHub: continuous_integration/scm/github.md
      - GitHub Enterprise: continuous_integration/scm/github_enterprise.md
      - Bitbucket: continuous_integration/scm/bitbucket.md
      - Bitbucket Server: continuous_integration/scm/bitbucket_server.md
      - GitLab: continuous_integration/scm/gitlab.md
    - Notifications:
      - Slack: continuous_integration/notifications/slack.md
      - Email: continuous_integration/notifications/email.md
      - HipChat: continuous_integration/notifications/hipchat.md
      - IRC: continuous_integration/notifications/irc.md
    - Image Registries:
      - Docker Hub: continuous_integration/image_registries/docker_hub.md
      - Docker Trusted Registry: continuous_integration/image_registries/docker_trusted_registry.md
      - Amazon EC2 Container Registry (ECR): continuous_integration/image_registries/amazon_ecr.md
      - Google Container Registry (GCR): continuous_integration/image_registries/google_gcr.md
      - Quay.io: continuous_integration/image_registries/quay.md
      - Any Private Registry: continuous_integration/image_registries/private_registry.md
    - Container Services:
      - Amazon EC2 Container Service (ECS): continuous_integration/container_services/amazon_ecs.md
      - Google Container Engine (GKE): continuous_integration/container_services/google_gke.md
      - Docker Cloud: continuous_integration/container_services/docker_cloud.md
      - Docker Datacenter: continuous_integration/container_services/docker_datacenter.md
    - Deploy:
      - AWS Elastic Beanstalk: continuous_integration/deploy/aws_eb.md
      - Webhooks: continuous_integration/deploy/webhooks.md
    - Keys:
      - SSH: continuous_integration/keys/ssh.md
      - PEM:  continuous_integration/keys/pem.md
  - Running builds on your own machines (BYON):
    - Overview: continuous_integration/byon/byon_overview.md
    - Setup: continuous_integration/byon/setup.md
  - Permissions: continuous_integration/permissions.md
  - Troubleshooting CI: continuous_integration/ci_troubleshoot.md
- Pipelines:
  - Overview: pipelines/overview.md
  - Resources: pipelines/resources.md
  - Jobs: pipelines/jobs.md
  - Triggers: pipelines/triggers.md
  - Deploying your first pipeline: tutorials/deploy_sample_pipeline.md
  - FAQ: pipelines/faq.md
- Navigating the UI:
  - Home Page: navigating_ui/homepage.md
  - Account Settings:
    - Accounts section: navigating_ui/account_settings.md
    - Integrations section: navigating_ui/account_settings.md
    - Cards section: navigating_ui/account_settings.md
    - Images section: navigating_ui/account_settings.md
    - API section: navigating_ui/account_settings.md
  - Subscriptions:
    - CI tab: navigating_ui/subscriptions_ci.md
    - Infra tab: navigating_ui/subscriptions_infra.md
    - Pipelines tab: navigating_ui/subscriptions_pipelines.md
    - Settings tab: navigating_ui/subscriptions_settings.md
  - Projects:
    - Status: navigating_ui/projects.md
    - Settings: navigating_ui/projects.md
  - Builds:
    - Test Coverage: navigating_ui/builds.md
    - Code Coverage: navigating_ui/builds.md
    - Console logs: navigating_ui/builds.md
- API: api.md
- Tutorials:
  - Pipelines:
    - How to add resources: tutorials/how_to_add_syncRepos.md
  - How to add integrations: tutorials/how_to_add_integrations.md
  - Running a sample CI build: tutorials/run_sample_ci_build.md
  - Deploying a sample appliation: tutorials/deploy_sample_pipeline.md
  - Source Control System:
    - Using GitHub: tutorials/how_to_use_github.md
    - Using GitHub Enterprise: tutorials/how_to_use_github_enterprise.md
    - Using Bitbucket: tutorials/how_to_use_bitbucket.md
    - Using Bitbucket Server: tutorials/how_to_use_bitbucket_server.md
    - Using GitLab: tutorials/how_to_use_gitlab.md
    - Linking GitHub and Bitbucket accounts: tutorials/link_github_and_bitbucket.md
  - Amazon:
    - Deploy to AWS CodeDeploy: tutorials/ht_codedeploy.md
    - Deploy to Amazon Opsworks: tutorials/ht_opsworks.md
    - Deploy to Amazon EC2 Container Registry (ECR): test.md
    - Deploy to AWS Elastic Beanstalk: test.md
    - Deploy to Amazon EC2 Container Service (ECS): test.md
  - Google:
    - Deploy to Google Container Registry (GCR): test.md
    - Deploy to Google Container Engine (GKE): test.md
  - Docker:
    - Deploy to Docker Hub: test.md
    - Deploy to Docker Trusted Registry: test.md
    - Deploy to Docker Datacenter: tutorials/ht_docker_datacenter.md
    - Deploy to Docker Cloud: test.md
  - Microsoft:
    - Deploy to DC/OS on Azure: test.md
    - Deploy to Docker Swarm on Azure: test.md
    - Deploy to Azure Container Service (ACS): test.md
  - Deploy to Quay.io: test.md
  - Deploy to any private registry: test.md
  - Languages Based:
    - test: test.md
  - Pushing to multiple registries: test.md
  - Pushing multiple tags: test.md
  - Overriding the default build image: test.md
  - Building your CI image: test.md
  - Pulling your CI image from a Docker registry: test.md
  - Setting up matrix builds: test.md
  - Setting up git submodules: test.md
  - Using Shippable_retry: test.md
  - Using Caching: test.md
  - Using matrix to parallelize builds: test.md
  - Running multiple docker push: test.md
  - Deploy to Heroku: tutorials/ht_heroku.md
  - Deploy to Digital Ocean: tutorials/ht_digitalocean.md
  - Monitor your Docker images for updates: tutorials/how_to_monitor_docker_images.md
