# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Overview:
  - What is Shippable?: index.md
  - FAQ: faq.md
- Continuous Integration (CI):
  - Overview: sources/continuous_integration/ci_overview.md
  - What is supported?: sources/continuous_integration/supported.md
  - Running your first build: run_first_build.md
  - Defaults:
    - Environment Variables: defaults/env_var.md
    - Images: defaults/images.md
    - Timeouts: defaults/timeouts.md
    - Node Machine Images: defaults/machine_images.md
  - Configuring your environment:
    - Languages:
      - Node.js: languages/node.md
      - Python: languages/python.md
      - Ruby:
        - GEMFILEs behaviour: languages/ruby.md
      - Java:
        - JDK behaviour: languages/java.md
      - Clojure: languages/clojure.md
      - Go: languages/go.md
      - PHP: languages/php.md
      - Scala: languages/scala.md
      - C: languages/objc.md
      - Custom Images: languages/custom_images.md
    - Advanced Options:
      - Custom Environment Variables: advanced_options/custom_env_var.md
      - Including/Excluding branches: advanced_options/include_exclude_branches.md
      - Matrix builds: advanced_options/matrix_builds.md
      - Caching: advanced_options/caching.md
      - Using git submodules: advanced_options/git_submodules.md
      - Shippable_retry: advanced_options/shippable_retry.md
  - Configuring your CI:
    - The ci section: build_ci.md
  - Configuring Post CI: post_ci.md
  - Integrations:
    - Source Control Systems:
      - GitHub: scm/github.md
      - GitHub Enterprise: scm/github_enterprise.md
      - Bitbucket: scm/bitbucket.md
      - Bitbucket Server: scm/bitbucket_server.md
      - GitLab: scm/gitlab.md
    - Notifications:
      - Slack: notifications/slack.md
      - Email: notifications/email.md
      - HipChat: notifications/hipchat.md
      - IRC: notifications/irc.md
    - Image Registries:
      - Docker Hub: image_registries/docker_hub.md
      - Docker Trusted Registry: image_registries/docker_trusted_registry.md
      - Amazon EC2 Container Registry (ECR): image_registries/amazon_ecr.md
      - Google Container Registry (GCR): image_registries/google_gcr.md
      - Quay.io: image_registries/quay.md
      - Any Private Registry: image_registries/private_registry.md
    - Container Services:
      - Amazon EC2 Container Service (ECS): container_services/amazon_ecs.md
      - Google Container Engine (GKE): container_services/google_gke.md
      - Docker Cloud: container_services/docker_cloud.md
      - Docker Datacenter: container_services/docker_datacenter.md
    - Deploy:
      - AWS Elastic Beanstalk: deploy/aws_eb.md
      - Webhooks: deploy/webhooks.md
    - Keys:
      - SSH: keys/ssh.md
      - PEM:  keys/pem.md
  - Running builds on your own machines (BYON):
    - Overview: byon/overview.md
    - Setup: byon/setup.md
  - Permissions: permissions.md
  - Troubleshooting CI: ci_troubleshoot.md
- Pipelines:
  - Overview: pipelines/overview.md
  - Resources: pipelines/resources.md
  - Jobs: pipelines/jobs.md
  - Triggers: pipelines/triggers.md
  - Deploying your first pipeline: gs_deploy_sample.md
  - FAQ: pipelines/faq.md
- Navigating the UI:
  - Home Page: navigating_ui/homepage.md
  - Account Settings: navigating_ui/accountsettings.md
  - Subscriptions:
    - CI tab: navigating_ui/subscriptions.md
    - Pipelines tab: navigating_ui/subscriptions.md
    - Settings: navigating_ui/subscriptions.md
  - Projects:
    - Status: navigating_ui/projects.md
    - Settings: navigating_ui/projects.md
  - Builds:
    - Test Coverage: navigating_ui/builds.md
    - Code Coverage: navigating_ui/builds.md
    - Console logs: navigating_ui/builds.md
- API: api.md
- Tutorials:
  - Pipelines:
    - How to add resources: tutorials/how_to_add_syncRepos.md
  - How to add integrations: tutorials/how_to_add_integrations.md
  - Running a sample CI build: gs_ci_sample.md
  - Deploying a sample appliation: test.md
  - Source Control System:
    - Using GitHub: test.md
    - Using GitHub Enterprise: test.md
    - Using Bitbucket: test.md
    - Using Bitbucket Server: ht_using_bitbucket_server.md
    - Using GitLab: ht_using_gitlab.md
    - Linking GitHub and Bitbucket accounts: ht_link_gh_and_bb.md
  - Amazon:
    - Deploy to AWS CodeDeploy: ht_codedeploy.md
    - Deploy to Amazon Opsworks: ht_opsworks.md
    - Deploy to Amazon EC2 Container Registry (ECR): test.md
    - Deploy to AWS Elastic Beanstalk: test.md
    - Deploy to Amazon EC2 Container Service (ECS): test.md
  - Google:
    - Deploy to Google Container Registry (GCR): test.md
    - Deploy to Google Container Engine (GKE): test.md
  - Docker:
    - Deploy to Docker Hub: test.md
    - Deploy to Docker Trusted Registry: test.md
    - Deploy to Docker Datacenter: ht_docker_datacenter.md
    - Deploy to Docker Cloud: test.md
  - Microsoft:
    - Deploy to DC/OS on Azure: test.md
    - Deploy to Docker Swarm on Azure: test.md
    - Deploy to Azure Container Service (ACS): test.md
  - Deploy to Quay.io: test.md
  - Deploy to any private registry: test.md
  - Languages Based:
    - test: test.md
  - Pushing to multiple registries: test.md
  - Pushing multiple tags: test.md
  - Overriding the default build image: test.md
  - Building your CI image: test.md
  - Pulling your CI image from a Docker registry: test.md
  - Setting up matrix builds: test.md
  - Setting up git submodules: test.md
  - Using Shippable_retry: test.md
  - Using Caching: test.md
  - Using matrix to parallelize builds: test.md
  - Running multiple docker push: test.md
  - Deploy to Heroku: ht_heroku.md
  - Deploy to Digital Ocean: ht_digitalocean.md
