# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Getting Started:
  - Overview: index.md
  - Concepts: gs_concepts.md
  - What is supported?: gs_supported.md
  - Pricing: gs_plans.md
  - Your Shippable Account: acc_overview.md
  - Run a sample CI build: gs_ci_sample.md
  - Deploy a sample application: gs_deploy_sample.md
- C I:
  - Overview: ci_overview.md
  - Subscriptions: ci_subscriptions.md
  - Projects: ci_projects.md
  - Builds: ci_builds.md
  - Configuring your build: ci_configure.md
  - Language help: ci_languages.md
  - Docker support: ci_docker.md
  - Running builds on your machines: ci_byoh.md
  - Running a sample build: gs_ci_sample.md
  - CI FAQ: ci_faq.md
  - CI Troubleshooting: ci_troubleshoot.md
- Pipelines:
  - Overview: pipelines_overview.md
  - Pipeline Status: pipelines_subscriptions.md
  - Configuring and managing pipelines: pipelines_configure.md
  - Deploy a sample app: gs_deploy_sample.md
  - Pipelines FAQ: pipelines_faq.md
- Integrations:
  - Overview: int_overview.md
  - Source control providers: int_scm.md
  - Docker registries: int_docker_registries.md
  - Container services: int_container_services.md
  - PaaS/IaaS providers: int_paas_iaas_providers.md
  - Notification providers: int_notifications.md
  - Keys: int_keys.md
- Lighthouse: lighthouse.md
- API: api.md
- Tutorials:
  - Overview: ht_overview.md
  - Using GitLab with Shippable: ht_using_gitlab.md
  - Linking GitHub and Bitbucket accounts: ht_link_gh_and_bb.md
  - Using Bitbucket Server with Shippable: ht_using_bitbucket_server.md
  - Deploy to Heroku: ht_heroku.md
  - Deploy to Amazon EC2: ht_codedeploy.md
  - Deploy to Digital Ocean: ht_digitalocean.md
  - Deploy to Amazon Opsworks: ht_opsworks.md
  - Deploy to Docker Datacenter: ht_docker_datacenter.md 
