# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Overview:
  - What is Shippable?: index.md
  - FAQ: faq.md
- Continuous Integration (CI):
  - Overview: ci_overview.md
  - What is supported?: gs_supported.md
  - Running your first build: test.md
  - Defaults:
    - Environment Variables: test.md
    - Images: test.md
    - Timeouts: test.md
    - Node Machine Images: test.md
  - Configuring your environment:
    - Languages:
      - Node.js: test.md
      - Python: test.md
      - Ruby:
        - GEMFILEs behaviour: test.md
      - Java:
        - JDK behaviour: test.md
      - Clojure: test.md
      - Go: test.md
      - PHP: test.md
      - Scala: test.md
      - C: test.md
      - Custom Images: test.md
    - Advanced Options:
      - Custom Environment Variables: test.md
      - Including/Excluding branches: test.md
      - Matrix builds: test.md
      - Caching: test.md
      - Using git submodules: test.md
      - Shippable_retry: test.md
  - Configuring your CI:
    - The ci section: test.md
  - Configuring Post CI: test.md
  - Integrations:
    - Notifications:
      - Slack: test.md
      - Email: test.md
      - HipChat: test.md
      - IRC: test.md
    - Image Registries:
      - Docker Hub: test.md
      - Docker Trusted Registry: test.md
      - Amazon EC2 Container Registry (ECR): test.md
      - Google Container Registry (GCR): test.md
      - Quay.io: test.md
      - Any Private Registry: test.md
    - Container Services:
      - Amazon EC2 Container Service (ECS): test.md
      - Google Container Engine (GKE): test.md
      - Docker Cloud: test.md
      - Docker Datacenter: test.md
    - Deploy:
      - AWS Elastic Beanstalk: test.md
      - Webhooks: test.md
    - Keys:
      - SSH: int_keys.md
      - PEM:  int_keys.md
  - Running builds on your own machines (BYON):
    - Overview: ci_byoh.md
    - Setup: test.md
  - Permissions: test.md
  - Troubleshooting CI: ci_troubleshoot.md
- Pipelines:
  - Overview: pipelines/overview.md
  - Resources: pipelines/resources.md
  - Deploying your first pipeline: gs_deploy_sample.md
  - FAQ: pipelines/faq.md
- Navigating the UI:
  - Home Page: test.md
  - Account Settings: test.md
  - Subscriptions:
    - CI tab: test.md
    - Pipelines tab: test.md
    - Settings: test.md
  - Projects:
    - Status: test.md
    - Settings: test.md
  - Builds:
    - Test Coverage: test.md
    - Code Coverage: test.md
    - Console logs: test.md
- API: api.md
- Tutorials:
  - Pipelines:
    - How to add resources: tutorials/how_to_add_syncRepos.md
  - How to add integrations: tutorials/how_to_add_integrations.md
  - Running a sample CI build: gs_ci_sample.md
  - Deploying a sample appliation: test.md
  - Source Control System:
    - Using GitHub: test.md
    - Using GitHub Enterprise: test.md
    - Using Bitbucket: test.md
    - Using Bitbucket Server: ht_using_bitbucket_server.md
    - Using GitLab: ht_using_gitlab.md
    - Linking GitHub and Bitbucket accounts: ht_link_gh_and_bb.md
  - Amazon:
    - Deploy to AWS CodeDeploy: ht_codedeploy.md
    - Deploy to Amazon Opsworks: ht_opsworks.md
    - Deploy to Amazon EC2 Container Registry (ECR): test.md
    - Deploy to AWS Elastic Beanstalk: test.md
    - Deploy to Amazon EC2 Container Service (ECS): test.md
  - Google:
    - Deploy to Google Container Registry (GCR): test.md
    - Deploy to Google Container Engine (GKE): test.md
  - Docker:
    - Deploy to Docker Hub: test.md
    - Deploy to Docker Trusted Registry: test.md
    - Deploy to Docker Datacenter: ht_docker_datacenter.md
    - Deploy to Docker Cloud: test.md
  - Microsoft:
    - Deploy to DC/OS on Azure: test.md
    - Deploy to Docker Swarm on Azure: test.md
    - Deploy to Azure Container Service (ACS): test.md
  - Deploy to Quay.io: test.md
  - Deploy to any private registry: test.md
  - Languages Based:
    - test: test.md
  - Pushing to multiple registries: test.md
  - Pushing multiple tags: test.md
  - Overriding the default build image: test.md
  - Building your CI image: test.md
  - Pulling your CI image from a Docker registry: test.md
  - Setting up matrix builds: test.md
  - Setting up git submodules: test.md
  - Using Shippable_retry: test.md
  - Using Caching: test.md
  - Using matrix to parallelize builds: test.md
  - Running multiple docker push: test.md
  - Deploy to Heroku: ht_heroku.md
  - Deploy to Digital Ocean: ht_digitalocean.md
